apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-pipeline
spec:
  replicas: 2
  selector:
    matchLabels:
      app: data-pipeline
  template:
    metadata:
      labels:
        app: data-pipeline
    spec:
      containers:
      - name: consumer
        image: python:3.8
        command: ["python", "/consumer/consumer.py"]
        volumeMounts:
        - name: scripts
          mountPath: /consumer
      volumes:
      - name: scripts
        hostPath:
          path: /mnt/data/scalable_data_pipeline/consumer
